//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class MycobotAnglesMsg : Message
    {
        public const string k_RosMessageName = "mycobot_communication/MycobotAngles";
        public override string RosMessageName => k_RosMessageName;

        public float[] joints;

        public MycobotAnglesMsg()
        {
            this.joints = new float[6];
        }

        public MycobotAnglesMsg(float[] joints)
        {
            this.joints = joints;
        }

        public static MycobotAnglesMsg Deserialize(MessageDeserializer deserializer) => new MycobotAnglesMsg(deserializer);

        private MycobotAnglesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(float), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "MycobotAnglesMsg: " +
            "\njoint_1: " + joints[0].ToString() +
            "\njoint_2: " + joints[1].ToString() +
            "\njoint_3: " + joints[2].ToString() +
            "\njoint_4: " + joints[3].ToString() +
            "\njoint_5: " + joints[4].ToString() +
            "\njoint_6: " + joints[4].ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
