//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class MycobotSetCoordsMsg : Message
    {
        public const string k_RosMessageName = "mycobot_communication/MycobotSetCoords";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;
        public float rx;
        public float ry;
        public float rz;
        public sbyte speed;
        public sbyte model;

        public MycobotSetCoordsMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.rx = 0.0f;
            this.ry = 0.0f;
            this.rz = 0.0f;
            this.speed = 0;
            this.model = 0;
        }

        public MycobotSetCoordsMsg(float x, float y, float z, float rx, float ry, float rz, sbyte speed, sbyte model)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.rx = rx;
            this.ry = ry;
            this.rz = rz;
            this.speed = speed;
            this.model = model;
        }

        public static MycobotSetCoordsMsg Deserialize(MessageDeserializer deserializer) => new MycobotSetCoordsMsg(deserializer);

        private MycobotSetCoordsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.rx);
            deserializer.Read(out this.ry);
            deserializer.Read(out this.rz);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.model);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.rx);
            serializer.Write(this.ry);
            serializer.Write(this.rz);
            serializer.Write(this.speed);
            serializer.Write(this.model);
        }

        public override string ToString()
        {
            return "MycobotSetCoordsMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nrx: " + rx.ToString() +
            "\nry: " + ry.ToString() +
            "\nrz: " + rz.ToString() +
            "\nspeed: " + speed.ToString() +
            "\nmodel: " + model.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
