//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class GetCoordsRequest : Message
    {
        public const string k_RosMessageName = "mycobot_communication/GetCoords";
        public override string RosMessageName => k_RosMessageName;


        public GetCoordsRequest()
        {
        }
        public static GetCoordsRequest Deserialize(MessageDeserializer deserializer) => new GetCoordsRequest(deserializer);

        private GetCoordsRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetCoordsRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
