//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class PumpStatusRequest : Message
    {
        public const string k_RosMessageName = "mycobot_communication/PumpStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool Status;
        public sbyte Pin1;
        public sbyte Pin2;

        public PumpStatusRequest()
        {
            this.Status = false;
            this.Pin1 = 0;
            this.Pin2 = 0;
        }

        public PumpStatusRequest(bool Status, sbyte Pin1, sbyte Pin2)
        {
            this.Status = Status;
            this.Pin1 = Pin1;
            this.Pin2 = Pin2;
        }

        public static PumpStatusRequest Deserialize(MessageDeserializer deserializer) => new PumpStatusRequest(deserializer);

        private PumpStatusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.Status);
            deserializer.Read(out this.Pin1);
            deserializer.Read(out this.Pin2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Status);
            serializer.Write(this.Pin1);
            serializer.Write(this.Pin2);
        }

        public override string ToString()
        {
            return "PumpStatusRequest: " +
            "\nStatus: " + Status.ToString() +
            "\nPin1: " + Pin1.ToString() +
            "\nPin2: " + Pin2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
